import { v } from "convex/values";
import { query, mutation, internalMutation, internalAction } from "./_generated/server";
import { Id } from "./_generated/dataModel";

/**
 * K-1 Records Table - Handles K-1 Pass-Through Syncing
 * 
 * This module manages K-1 data generated by partnerships (Form 1065) and 
 * S-Corporations (Form 1120S) and syncs it to individual owners' 1040 returns.
 * 
 * K-1 data flows through:
 * Business Return (1065/1120S) -> K-1 Records -> Individual 1040 Return
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

/**
 * K-1 Data structure containing all K-1 fields
 * form These fields flow from Schedule K-1 (Form 1065 or 1120S) to the recipient's 1040
 */
export interface K1Data {
  // Income items (Box 1-7)
  ordinaryBusinessIncome?: number;
  qualifiedBusinessIncome?: number;
  section199ADeduction?: number;
  
  // Box 8 - Specific Deductions
  charitableContributions?: number;
  investmentInterest?: number;
  section179Deduction?: number;
  otherDeductions?: number;
  
  // Box 9 - Tax Exempt Income
  taxExemptInterest?: number;
  exemptQualifiedDividends?: number;
  
  // Box 10 - Credits
  foreignTaxCredit?: number;
  otherCredits?: number;
  
  // Box 11 - Other Items
  ordinaryDividends?: number;
  qualifiedDividends?: number;
  section409ATaxDeferral?: number;
  otherItems?: number;
  
  // Box 12 - Supplemental Information
  section199AQualifiedBusinessIncome?: number;
  section199AQualifiedProperty?: number;
  section199AWages?: number;
  
  // Additional K-1 fields
  selfEmploymentEarnings?: number;
  selfEmploymentDeductions?: number;
  healthInsurance?: number;
  sepSIMPLE?: number;
  qualifiedPlanExpenses?: number;
  
  // Investment items
  interestIncome?: number;
  shortTermCapitalGains?: number;
  longTermCapitalGains?: number;
  section1231Gains?: number;
  section1231Losses?: number;
  
  // Rental real estate
  rentalRealEstateIncome?: number;
  rentalRealEstateExpenses?: number;
  
  // Other income/expenses
  otherIncome?: number;
  otherExpenses?: number;
}

export type SyncStatus = "pending" | "synced" | "error";

// =============================================================================
// QUERY FUNCTIONS
// =============================================================================

/**
 * Get a specific K-1 record by ID
 */
export const getK1Record = query({
  args: { id: v.id("k1Records") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

/**
 * Get all K-1 records for a business return (1065/1120S)
 */
export const getK1RecordsByReturn = query({
  args: { returnId: v.id("returns") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("k1Records")
      .withIndex("by_return", (q) => q.eq("returnId", args.returnId))
      .collect();
  },
});

/**
 * Get all K-1 records for a specific partner/owner
 */
export const getK1RecordsByPartner = query({
  args: { partnerId: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("k1Records")
      .withIndex("by_partnerId", (q) => q.eq("partnerId", args.partnerId))
      .collect();
  },
});

/**
 * Get K-1 records filtered by sync status (pending, synced, error)
 */
export const getK1RecordsByStatus = query({
  args: { syncStatus: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("k1Records")
      .withIndex("by_syncStatus", (q) => q.eq("syncStatus", args.syncStatus))
      .collect();
  },
});

/**
 * Get all K-1 records that need to be synced
 */
export const getPendingK1Sync = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db
      .query("k1Records")
      .withIndex("by_syncStatus", (q) => q.eq("syncStatus", "pending"))
      .collect();
  },
});

/**
 * List all K-1 records with pagination
 */
export const listK1Records = query({
  args: { 
    limit: v.optional(v.number()),
    cursor: v.optional(v.id("k1Records")),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 50;
    const { cursor } = args;
    
    let query = ctx.db.query("k1Records").order("desc");
    
    if (cursor) {
      // Get the record at the cursor to use as a starting point
      const cursorRecord = await ctx.db.get(cursor);
      if (cursorRecord) {
        query = query.filter((q) => q.lt("_creationTime", cursorRecord._creationTime));
      }
    }
    
    const results = await query.take(limit);
    
    // Determine if there are more results
    const hasMore = results.length === limit;
    const nextCursor = hasMore ? results[results.length - 1]._id : null;
    
    return {
      results,
      hasMore,
      nextCursor,
    };
  },
});

/**
 * Get K-1 record by return and partner combination
 */
export const getK1RecordByReturnAndPartner = query({
  args: { 
    returnId: v.id("returns"), 
    partnerId: v.string() 
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("k1Records")
      .withIndex("by_return", (q) => q.eq("returnId", args.returnId))
      .filter((q) => q.eq(q.field("partnerId"), args.partnerId))
      .first();
  },
});

// =============================================================================
// MUTATION FUNCTIONS - CRUD OPERATIONS
// =============================================================================

/**
 * Create a new K-1 record
 * 
 * This is called when:
 * - A partnership return (1065) is processed and K-1s need to be generated
 * - An S-Corporation return (1120S) is processed and K-1s need to be generated
 * - Manual K-1 entry is performed
 */
export const createK1Record = mutation({
  args: {
    returnId: v.id("returns"),
    partnerId: v.string(),
    ein: v.string(),
    recipientName: v.string(),
    recipientTin: v.string(),
    k1Data: v.any(),
    syncStatus: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    
    const k1RecordId = await ctx.db.insert("k1Records", {
      returnId: args.returnId,
      partnerId: args.partnerId,
      ein: args.ein,
      recipientName: args.recipientName,
      recipientTin: args.recipientTin,
      k1Data: args.k1Data,
      syncStatus: args.syncStatus ?? "pending",
      syncedAt: undefined,
      createdAt: now,
    });
    
    return k1RecordId;
  },
});

/**
 * Update an existing K-1 record
 */
export const updateK1Record = mutation({
  args: {
    id: v.id("k1Records"),
    ein: v.optional(v.string()),
    recipientName: v.optional(v.string()),
    recipientTin: v.optional(v.string()),
    k1Data: v.optional(v.any()),
    syncStatus: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const { id, ...updates } = args;
    
    // Get existing record to check current state
    const existing = await ctx.db.get(id);
    if (!existing) {
      throw new Error(`K-1 record not found: ${id}`);
    }
    
    // Clear syncedAt if status changed from synced
    if (updates.syncStatus && updates.syncStatus !== existing.syncStatus) {
      if (updates.syncStatus === "pending") {
        updates.syncedAt = undefined;
      }
    }
    
    await ctx.db.patch(id, updates);
    
    return { success: true };
  },
});

/**
 * Mark a K-1 record as synced with timestamp
 */
export const markK1Synced = mutation({
  args: { id: v.id("k1Records") },
  handler: async (ctx, args) => {
    const now = Date.now();
    
    await ctx.db.patch(args.id, {
      syncStatus: "synced",
      syncedAt: now,
    });
    
    return { success: true, syncedAt: now };
  },
});

/**
 * Mark a K-1 record as errored
 */
export const markK1Error = mutation({
  args: { 
    id: v.id("k1Records"),
    errorMessage: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.id, {
      syncStatus: "error",
    });
    
    // Note: Could also store error message in k1Data or separate field
    // For now, error details would need to be retrieved from audit logs
    
    return { success: true };
  },
});

/**
 * Delete a K-1 record
 */
export const deleteK1Record = mutation({
  args: { id: v.id("k1Records") },
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id);
    return { success: true };
  },
});

// =============================================================================
// K-1 SYNC FUNCTIONS - CORE BUSINESS LOGIC
// =============================================================================

/**
 * Generate K-1 records for all partners from a 1065 partnership return
 * 
 * This function:
 * 1. Queries the partnership return for partner information
 * 2. Creates K-1 records for each partner
 * 3. Extracts Schedule K-1 data from the 1065 return
 */
export const generateK1FromPartnership = internalMutation({
  args: {
    partnershipReturnId: v.id("returns"),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    // Get the partnership return
    const partnershipReturn = await ctx.db.get(args.partnershipReturnId);
    if (!partnershipReturn) {
      throw new Error(`Partnership return not found: ${args.partnershipReturnId}`);
    }
    
    // Get all form instances for this return (to find Schedule K-1 data)
    const formInstances = await ctx.db
      .query("formInstances")
      .withIndex("by_return", (q) => q.eq("returnId", args.partnershipReturnId))
      .collect();
    
    // Look for Schedule K-1 form instances
    const k1FormInstances = formInstances.filter(
      (f) => f.formType === "ScheduleK1" || f.formType === "K1"
    );
    
    // For each K-1 form instance, create a K-1 record
    const createdK1Ids: string[] = [];
    
    for (const k1Form of k1FormInstances) {
      // Get all fields for this K-1 form
      const k1Fields = await ctx.db
        .query("fields")
        .withIndex("by_instance", (q) => q.eq("instanceId", k1Form.instanceId))
        .collect();
      
      // Extract K-1 data
      const k1Data: K1Data = {};
      
      for (const field of k1Fields) {
        switch (field.fieldKey) {
          case "ordinaryBusinessIncome":
          case "box1":
            k1Data.ordinaryBusinessIncome = field.value as number;
            break;
          case "qualifiedBusinessIncome":
          case "box2":
            k1Data.qualifiedBusinessIncome = field.value as number;
            break;
          case "section199ADeduction":
          case "box3":
            k1Data.section199ADeduction = field.value as number;
            break;
          case "charitableContributions":
          case "box5a":
            k1Data.charitableContributions = field.value as number;
            break;
          case "investmentInterest":
          case "box5c":
            k1Data.investmentInterest = field.value as number;
            break;
          case "section179Deduction":
          case "box5d":
            k1Data.section179Deduction = field.value as number;
            break;
          case "foreignTaxCredit":
          case "box6":
            k1Data.foreignTaxCredit = field.value as number;
            break;
          case "ordinaryDividends":
          case "box4a":
            k1Data.ordinaryDividends = field.value as number;
            break;
          case "qualifiedDividends":
          case "box4b":
            k1Data.qualifiedDividends = field.value as number;
            break;
          case "box7":
          case "otherDeductions":
            k1Data.otherDeductions = field.value as number;
            break;
          // Partner info stored in instance name or specific fields
          case "partnerName":
            // This would need to be extracted from form
            break;
          case "partnerTin":
            // This would need to be extracted from form
            break;
        }
      }
      
      // Extract partner info from the form instance
      // In a real implementation, this would come from the Schedule K-1 partner info
      const partnerId = k1Form.instanceName || ""; // Would need actual partner ID
      const recipientName = k1Form.instanceName || "Unknown Partner";
      const recipientTin = ""; // Would need to extract from K-1 fields
      const ein = ""; // Would need to extract from K-1 fields
      
      // Create the K-1 record
      const k1Id = await ctx.db.insert("k1Records", {
        returnId: args.partnershipReturnId,
        partnerId,
        ein,
        recipientName,
        recipientTin,
        k1Data,
        syncStatus: "pending",
        createdAt: Date.now(),
      });
      
      createdK1Ids.push(k1Id);
      
      // Log the K-1 generation
      await ctx.db.insert("auditLogs", {
        returnId: args.partnershipReturnId,
        userId: args.userId,
        action: "K-1 Generated",
        fieldKey: k1Form.instanceId,
        previousValue: null,
        newValue: k1Data,
        source: "calculated",
        timestamp: Date.now(),
      });
    }
    
    return {
      success: true,
      createdCount: createdK1Ids.length,
      k1RecordIds: createdK1Ids,
    };
  },
});

/**
 * Generate K-1 records for all shareholders from an 1120S return
 * 
 * Similar to partnership but for S-Corporations
 */
export const generateK1FromSCorporation = internalMutation({
  args: {
    sCorpReturnId: v.id("returns"),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    // Get the S-Corporation return
    const sCorpReturn = await ctx.db.get(args.sCorpReturnId);
    if (!sCorpReturn) {
      throw new Error(`S-Corporation return not found: ${args.sCorpReturnId}`);
    }
    
    // Get all form instances for this return
    const formInstances = await ctx.db
      .query("formInstances")
      .withIndex("by_return", (q) => q.eq("returnId", args.sCorpReturnId))
      .collect();
    
    // Look for Schedule K-1 form instances
    const k1FormInstances = formInstances.filter(
      (f) => f.formType === "ScheduleK1" || f.formType === "K1"
    );
    
    const createdK1Ids: string[] = [];
    
    for (const k1Form of k1FormInstances) {
      // Get fields for this K-1
      const k1Fields = await ctx.db
        .query("fields")
        .withIndex("by_instance", (q) => q.eq("instanceId", k1Form.instanceId))
        .collect();
      
      // Extract K-1 data
      const k1Data: K1Data = {};
      
      for (const field of k1Fields) {
        switch (field.fieldKey) {
          case "ordinaryBusinessIncome":
          case "box1":
            k1Data.ordinaryBusinessIncome = field.value as number;
            break;
          case "qualifiedBusinessIncome":
          case "box2":
            k1Data.qualifiedBusinessIncome = field.value as number;
            break;
          case "section199ADeduction":
          case "box3":
            k1Data.section199ADeduction = field.value as number;
            break;
          case "charitableContributions":
          case "box5a":
            k1Data.charitableContributions = field.value as number;
            break;
          case "investmentInterest":
          case "box5c":
            k1Data.investmentInterest = field.value as number;
            break;
          case "ordinaryDividends":
          case "box4a":
            k1Data.ordinaryDividends = field.value as number;
            break;
          case "qualifiedDividends":
          case "box4b":
            k1Data.qualifiedDividends = field.value as number;
            break;
        }
      }
      
      const partnerId = k1Form.instanceName || "";
      const recipientName = k1Form.instanceName || "Unknown Shareholder";
      
      const k1Id = await ctx.db.insert("k1Records", {
        returnId: args.sCorpReturnId,
        partnerId,
        ein: "",
        recipientName,
        recipientTin: "",
        k1Data,
        syncStatus: "pending",
        createdAt: Date.now(),
      });
      
      createdK1Ids.push(k1Id);
    }
    
    return {
      success: true,
      createdCount: createdK1Ids.length,
      k1RecordIds: createdK1Ids,
    };
  },
});

/**
 * Sync a single K-1 record to the partner's 1040 return
 * 
 * This is the core function that:
 * 1. Gets the K-1 record data
 * 2. Finds or creates the appropriate form instances in the 1040 return
 * 3. Maps K-1 fields to 1040 fields (e.g., K-1 ordinary income -> 1040 Schedule E)
 * 4. Updates the individual return with the K-1 data
 * 5. Logs the sync in auditLogs with source "k1_sync"
 */
export const syncK1ToIndividual = internalMutation({
  args: {
    k1RecordId: v.id("k1Records"),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    // Get the K-1 record
    const k1Record = await ctx.db.get(args.k1RecordId);
    if (!k1Record) {
      throw new Error(`K-1 record not found: ${args.k1RecordId}`);
    }
    
    // Skip if already synced
    if (k1Record.syncStatus === "synced") {
      return { success: true, message: "Already synced" };
    }
    
    const k1Data = k1Record.k1Data as K1Data;
    
    // Get the partner's individual return - partnerId is the individual return ID
    const partnerReturnId = k1Record.partnerId as string;
    const individualReturn = await ctx.db.get(partnerReturnId as Id<"returns">);
    if (!individualReturn) {
      // Mark as error - partner return not found
      await ctx.db.patch(args.k1RecordId, { syncStatus: "error" });
      
      await ctx.db.insert("auditLogs", {
        returnId: k1Record.returnId,
        userId: args.userId,
        action: "K-1 Sync Error",
        previousValue: null,
        newValue: { error: "Partner return not found", partnerId: k1Record.partnerId },
        source: "k1_sync",
        timestamp: Date.now(),
      });
      
      return { success: false, error: "Partner return not found" };
    }
    
    // Find or create Schedule E (Supplemental Income and Loss) for partnership/S-corp income
    let scheduleE = await ctx.db
      .query("formInstances")
      .withIndex("by_return", (q) => q.eq("returnId", partnerReturnId as Id<"returns">))
      .filter((q) => q.eq(q.field("formType"), "ScheduleE"))
      .first();
    
    if (!scheduleE) {
      // Create Schedule E instance
      const instanceId = await ctx.db.insert("formInstances", {
        returnId: partnerReturnId as Id<"returns">,
        formType: "ScheduleE",
        instanceName: "Schedule E - Supplemental Income",
        status: "In Progress",
        documentSource: "calculated",
      });
      scheduleE = await ctx.db.get(instanceId);
    }
    
    // Map K-1 fields to Schedule E fields
    // Part II - Income or Loss from Partnerships and S Corporations
    const scheduleEFields: { fieldKey: string; value: any }[] = [];
    
    // Ordinary business income (Box 1) -> Schedule E Line 2
    if (k1Data.ordinaryBusinessIncome !== undefined) {
      scheduleEFields.push({
        fieldKey: "line2_partnership",
        value: k1Data.ordinaryBusinessIncome,
      });
    }
    
    // Section 199A deduction (Box 3) -> Schedule E Line 2
    if (k1Data.section199ADeduction !== undefined) {
      scheduleEFields.push({
        fieldKey: "line2_section199A",
        value: k1Data.section199ADeduction,
      });
    }
    
    // Charitable contributions -> Schedule E Line 3
    if (k1Data.charitableContributions !== undefined) {
      scheduleEFields.push({
        fieldKey: "line3_charitable",
        value: k1Data.charitableContributions,
      });
    }
    
    // Investment interest -> Schedule E Line 3
    if (k1Data.investmentInterest !== undefined) {
      scheduleEFields.push({
        fieldKey: "line3_investment",
        value: k1Data.investmentInterest,
      });
    }
    
    // Update or create fields in Schedule E
    for (const fieldUpdate of scheduleEFields) {
      const existingField = await ctx.db
        .query("fields")
        .withIndex("by_instance", (q) => q.eq("instanceId", scheduleE!._id))
        .filter((q) => q.eq(q.field("fieldKey"), fieldUpdate.fieldKey))
        .first();
      
      if (existingField) {
        // Update existing field
        await ctx.db.patch(existingField._id, {
          value: fieldUpdate.value,
          isManualOverride: false,
          isCalculated: true,
        });
      } else {
        // Create new field
        await ctx.db.insert("fields", {
          instanceId: scheduleE!._id,
          fieldKey: fieldUpdate.fieldKey,
          value: fieldUpdate.value,
          isManualOverride: false,
          isCalculated: true,
        });
      }
    }
    
    // Also check for dividend income that goes to Form 1040 Schedule B
    if (k1Data.ordinaryDividends !== undefined || k1Data.qualifiedDividends !== undefined) {
      // Look for Schedule B or update 1040 directly
      // For simplicity, we'll track this in audit log
    }
    
    // Mark the K-1 as synced
    const now = Date.now();
    await ctx.db.patch(args.k1RecordId, {
      syncStatus: "synced",
      syncedAt: now,
    });
    
    // Log the sync in auditLogs with source "k1_sync" for audit trail
    await ctx.db.insert("auditLogs", {
      returnId: partnerReturnId as Id<"returns">,
      userId: args.userId,
      action: "K-1 Sync",
      previousValue: null,
      newValue: {
        k1RecordId: args.k1RecordId,
        businessReturnId: k1Record.returnId,
        k1Data,
        syncedAt: now,
      },
      source: "k1_sync",
      timestamp: now,
    });
    
    return {
      success: true,
      syncedAt: now,
      fieldsUpdated: scheduleEFields.length,
    };
  },
});

/**
 * Sync all pending K-1 records
 * 
 * This is typically run:
 * - After a business return is completed
 * - On a schedule (e.g., nightly sync)
 * - Manually by a preparer
 */
export const syncAllPendingK1s = internalMutation({
  args: { userId: v.string() },
  handler: async (ctx, args) => {
    // Get all pending K-1 records
    const pendingK1s = await ctx.db
      .query("k1Records")
      .withIndex("by_syncStatus", (q) => q.eq("syncStatus", "pending"))
      .collect();
    
    const results = {
      total: pendingK1s.length,
      succeeded: 0,
      failed: 0,
      errors: [] as string[],
    };
    
    for (const k1Record of pendingK1s) {
      try {
        // Get the K-1 record with latest data
        const k1 = await ctx.db.get(k1Record._id);
        if (!k1) {
          results.failed++;
          results.errors.push(`K-1 record not found: ${k1Record._id}`);
          continue;
        }
        
        // Skip if already synced (could have been synced by another process)
        if (k1.syncStatus === "synced") {
          results.succeeded++;
          continue;
        }
        
        // Sync the K-1 to the individual return
        const syncResult = await ctx.db.transaction(async (tx) => {
          // Get the K-1 record again within transaction
          const k1Data = k1.k1Data as K1Data;
          
          // Get the partner's individual return
          const partnerIdString = k1.partnerId as string;
          const individualReturn = await tx.get(partnerIdString as Id<"returns">);
          if (!individualReturn) {
            await tx.patch(k1._id, { syncStatus: "error" });
            return { success: false, error: "Partner return not found" };
          }
          
          // Find or create Schedule E
          let scheduleE = await tx
            .query("formInstances")
            .withIndex("by_return", (q) => q.eq("returnId", partnerIdString as Id<"returns">))
            .filter((q) => q.eq(q.field("formType"), "ScheduleE"))
            .first();
          
          if (!scheduleE) {
            const instanceId = await tx.insert("formInstances", {
              returnId: partnerIdString as Id<"returns">,
              formType: "ScheduleE",
              instanceName: "Schedule E - Supplemental Income",
              status: "In Progress",
              documentSource: "calculated",
            });
            scheduleE = await tx.get(instanceId);
          }
          
          // Map K-1 fields to Schedule E fields
          const updates: { fieldKey: string; value: any }[] = [];
          
          if (k1Data.ordinaryBusinessIncome !== undefined) {
            updates.push({ fieldKey: "line2_partnership", value: k1Data.ordinaryBusinessIncome });
          }
          if (k1Data.section199ADeduction !== undefined) {
            updates.push({ fieldKey: "line2_section199A", value: k1Data.section199ADeduction });
          }
          if (k1Data.charitableContributions !== undefined) {
            updates.push({ fieldKey: "line3_charitable", value: k1Data.charitableContributions });
          }
          
          // Apply updates
          for (const update of updates) {
            const existing = await tx
              .query("fields")
              .withIndex("by_instance", (q) => q.eq("instanceId", scheduleE!._id))
              .filter((q) => q.eq(q.field("fieldKey"), update.fieldKey))
              .first();
            
            if (existing) {
              await tx.patch(existing._id, {
                value: update.value,
                isManualOverride: false,
                isCalculated: true,
              });
            } else {
              await tx.insert("fields", {
                instanceId: scheduleE!._id,
                fieldKey: update.fieldKey,
                value: update.value,
                isManualOverride: false,
                isCalculated: true,
              });
            }
          }
          
          // Mark as synced
          const now = Date.now();
          await tx.patch(k1._id, {
            syncStatus: "synced",
            syncedAt: now,
          });
          
          // Log the sync
          await tx.insert("auditLogs", {
            returnId: partnerIdString as Id<"returns">,
            userId: args.userId,
            action: "K-1 Sync",
            previousValue: null,
            newValue: {
              k1RecordId: k1._id,
              businessReturnId: k1.returnId,
              syncedAt: now,
            },
            source: "k1_sync",
            timestamp: now,
          });
          
          return { success: true, syncedAt: now };
        });
        
        if (syncResult.success) {
          results.succeeded++;
        } else {
          results.failed++;
          results.errors.push(syncResult.error || "Unknown error");
        }
      } catch (error) {
        results.failed++;
        results.errors.push(`Error syncing K-1 ${k1Record._id}: ${error}`);
        
        // Mark as error
        await ctx.db.patch(k1Record._id, { syncStatus: "error" });
      }
    }
    
    return results;
  },
});

/**
 * Get audit trail for K-1 syncs for a return
 * 
 * Returns all K-1 sync events for a business return or individual return
 */
export const getK1AuditTrail = query({
  args: { returnId: v.id("returns") },
  handler: async (ctx, args) => {
    // Get K-1 records for this return
    const k1Records = await ctx.db
      .query("k1Records")
      .withIndex("by_return", (q) => q.eq("returnId", args.returnId))
      .collect();
    
    // Get audit logs for K-1 sync actions
    const auditLogs = await ctx.db
      .query("auditLogs")
      .withIndex("by_return", (q) => q.eq("returnId", args.returnId))
      .filter((q) => q.eq(q.field("action"), "K-1 Sync"))
      .order("desc")
      .take(100);
    
    return {
      k1Records: k1Records.map(k1 => ({
        id: k1._id,
        recipientName: k1.recipientName,
        syncStatus: k1.syncStatus,
        syncedAt: k1.syncedAt,
        createdAt: k1.createdAt,
      })),
      syncAuditLogs: auditLogs,
    };
  },
});

// =============================================================================
// SAMPLE SEED DATA
// =============================================================================

/**
 * Sample K-1 record for a partnership with 2 partners
 * 
 * This demonstrates typical K-1 data structure for:
 * - A partnership (Form 1065) with $150,000 ordinary business income
 * - Two partners splitting income equally
 * - Various deductions and credits
 */
export const sampleK1Data: K1Data = {
  // Income (Boxes 1-3)
  ordinaryBusinessIncome: 150000,
  qualifiedBusinessIncome: 150000,
  section199ADeduction: 0,
  
  // Deductions (Box 5)
  charitableContributions: 2500,
  investmentInterest: 500,
  section179Deduction: 0,
  otherDeductions: 0,
  
  // Tax Exempt Income (Box 6)
  taxExemptInterest: 0,
  exemptQualifiedDividends: 0,
  
  // Credits (Box 6)
  foreignTaxCredit: 0,
  otherCredits: 0,
  
  // Dividends (Box 4)
  ordinaryDividends: 0,
  qualifiedDividends: 0,
  
  // Section 199A (Box 11)
  section199AQualifiedBusinessIncome: 150000,
  section199AWages: 80000,
  section199AQualifiedProperty: 0,
  
  // Self Employment
  selfEmploymentEarnings: 150000,
  selfEmploymentDeductions: 0,
  healthInsurance: 0,
  sepSIMPLE: 0,
  qualifiedPlanExpenses: 0,
  
  // Investment
  interestIncome: 0,
  shortTermCapitalGains: 0,
  longTermCapitalGains: 0,
  
  // Other
  otherIncome: 0,
  otherExpenses: 0,
};

/**
 * Sample K-1 records for a 2-partner partnership
 * 
 * Partnership: ABC Consulting LLC (EIN: 12-3456789)
 * Partnership Return ID: Would be created in returns table
 * Partner 1: John Smith (SSN: 123-45-6789)
 * Partner 2: Jane Smith (SSN: 987-65-4321)
 */
export const sampleK1Records = [
  {
    partnerId: "partner_001", // Individual return ID for John Smith
    ein: "12-3456789",
    recipientName: "John Smith",
    recipientTin: "123-45-6789",
    k1Data: {
      ...sampleK1Data,
      ordinaryBusinessIncome: 75000, // 50% of partnership income
      qualifiedBusinessIncome: 75000,
      selfEmploymentEarnings: 75000,
      section199AQualifiedBusinessIncome: 75000,
      section199AWages: 40000,
    },
    syncStatus: "pending" as SyncStatus,
  },
  {
    partnerId: "partner_002", // Individual return ID for Jane Smith
    ein: "12-3456789",
    recipientName: "Jane Smith",
    recipientTin: "987-65-4321",
    k1Data: {
      ...sampleK1Data,
      ordinaryBusinessIncome: 75000, // 50% of partnership income
      qualifiedBusinessIncome: 75000,
      selfEmploymentEarnings: 75000,
      section199AQualifiedBusinessIncome: 75000,
      section199AWages: 40000,
    },
    syncStatus: "pending" as SyncStatus,
  },
];

/**
 * Seed sample K-1 data for testing
 * 
 * Usage: Import and call this function to create sample K-1 records
 */
export const seedSampleK1Data = mutation({
  args: { 
    businessReturnId: v.id("returns"),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const createdIds: string[] = [];
    const now = Date.now();
    
    for (const sample of sampleK1Records) {
      const id = await ctx.db.insert("k1Records", {
        returnId: args.businessReturnId,
        partnerId: sample.partnerId,
        ein: sample.ein,
        recipientName: sample.recipientName,
        recipientTin: sample.recipientTin,
        k1Data: sample.k1Data,
        syncStatus: sample.syncStatus,
        createdAt: now,
      });
      
      createdIds.push(id);
    }
    
    // Log the seeding
    await ctx.db.insert("auditLogs", {
      returnId: args.businessReturnId,
      userId: args.userId,
      action: "K-1 Seed Data",
      previousValue: null,
      newValue: { count: createdIds.length },
      source: "system",
      timestamp: now,
    });
    
    return {
      success: true,
      createdCount: createdIds.length,
      k1RecordIds: createdIds,
    };
  },
});
