"use client";

import "@/styles/form1040.css";
import { format } from "date-fns";

interface Field {
    fieldKey: string;
    value: any;
}

export function Form1040Print({ fields, taxpayerName }: { fields: Field[], taxpayerName: string }) {
    const getVal = (key: string) => {
        const field = fields.find(f => f.fieldKey === `1040_Line${key}` || f.fieldKey === key);
        if (!field) return "";
        const val = field.value;
        if (typeof val === "number") return val.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 });
        return val?.toString() || "";
    };

    return (
        <div className="form-1040-page print-only hidden">
            <div className="f1040-header flex justify-between items-baseline">
                <div>
                    <h1 className="text-2xl font-black italic">1040</h1>
                    <span className="text-[7pt] font-bold uppercase">U.S. Individual Income Tax Return</span>
                </div>
                <div className="text-right">
                    <span className="text-3xl font-black">2023</span>
                </div>
            </div>

            <div className="border border-black p-2 mb-4">
                <div className="flex justify-between border-b border-black pb-1 mb-1">
                    <div className="text-[8pt] font-bold">Taxpayer Name: <span className="font-mono text-[10pt] uppercase ml-2">{taxpayerName}</span></div>
                    <div className="text-[8pt] font-bold">Date: {format(new Date(), "MM/dd/yyyy")}</div>
                </div>
            </div>

            <div className="f1040-section-title">Income</div>
            <div className="space-y-0 relative min-h-[6in]">
                <PrintLine num="1z" label="Wages, salaries, tips, etc. Attach Form(s) W-2" value={getVal("Line1z")} />
                <PrintLine num="2b" label="Taxable interest" value={getVal("Line2b")} />
                <PrintLine num="3b" label="Ordinary dividends" value={getVal("Line3b")} />
                <PrintLine num="7" label="Capital gain or (loss). Attach Schedule D if required" value={getVal("Line7")} />
                <PrintLine num="8" label="Other income from Schedule 1, line 10" value={getVal("Line8")} />
                <PrintLine num="9" label="Total income. Add lines 1z, 2b, 3b, 4b, 5b, 6b, 7, and 8" value={getVal("Line9")} isTotal />
                <PrintLine num="10" label="Adjustments to income from Schedule 1, line 26" value={getVal("Line10")} />
                <PrintLine num="11" label="Adjusted gross income. Subtract line 10 from line 9" value={getVal("Line11")} isTotal />
                <PrintLine num="12" label="Standard deduction or itemized deductions (from Schedule A)" value={getVal("Line12")} />
                <PrintLine num="15" label="Taxable income. Subtract line 14 from line 11. If zero or less, enter -0-" value={getVal("Line15")} isTotal />

                <div className="mt-8">
                    <PrintLine num="16" label="Tax (see instructions)" value={getVal("Line16")} />
                    <PrintLine num="24" label="Total tax. Add lines 22 and 23" value={getVal("Line24")} isTotal />
                </div>

                <div className="mt-8 border-t-2 border-black pt-4">
                    <div className="flex justify-between items-center px-4">
                        <div className="text-xl font-black uppercase">Refund Amount</div>
                        <div className="text-2xl font-mono underline decoration-double">${getVal("RefundAmount")}</div>
                    </div>
                </div>
            </div>

            <div className="absolute bottom-4 left-4 text-[6pt] text-slate-400 italic">
                Generated by Phoenix Tax Pro - IRS Approved MeF Engine v1.0.4
            </div>
        </div>
    );
}

function PrintLine({ num, label, value, isTotal = false }: { num: string, label: string, value: string, isTotal?: boolean }) {
    return (
        <div className={`f1040-line ${isTotal ? 'bg-slate-50' : ''}`}>
            <span className="f1040-line-num">{num}</span>
            <span className="f1040-line-label">{label}</span>
            <span className="f1040-line-value">{value}</span>
        </div>
    );
}
